# Используем официальный образ Python
FROM python:3.12.4

# Устанавливаем рабочую директорию
WORKDIR /bot

# Копируем файл зависимостей
COPY ./requirements.txt /bot/requirements.txt

# Устанавливаем зависимости
RUN pip install --no-cache-dir --upgrade setuptools
RUN pip install --no-cache-dir --upgrade -r /bot/requirements.txt
RUN pip install --no-cache-dir python-multipart

# Копируем весь код бота
COPY ./ /bot

# Команда для запуска бота
CMD ["python", "aiogram_run.py"]
